FROM golang:1.17-alpine

LABEL MAINTAINER="Cloudflying" \
    MAIL="oss@live.hk"

ENV GOPATH /go
ENV GOBIN ${GOPATH}/bin
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOBIN

CMD [ "/bin/sh" ]
