FROM daocloud.io/library/xenial-cn
MAINTAINER Xiekers <im@xieke.org>
RUN mv /etc/apt/sources.list /etc/apt/source.list.bak && wget http://dl.xieke.org/conf/sources.list -O /etc/apt/sources.list
CMD ["/bin/bash"]
