FROM imxieke/archlinux:base
LABEL MAINTAINER="Cloudflying" \
        MAIL="<oss@live.hk>"

# RUN pacman -Syyu --force --noconfirm \
    # && pacman -Scc --noconfirm \
    # && rm -fr /var/cache/pacman/pkg/* \
    # && rm -fr /var/lib/pacman/*

CMD /bin/bash