FROM logstash:7.17.5

LABEL MAINTAINER="Cloudflying" \
    MAIL="oss@live.hk" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv

EXPOSE 9600 5044
ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
