FROM ghcr.io/dockenv/alpine:3.16

LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description='Nginx Unit'

RUN apk add --no-cache unit unit-php8 unit-python3
