# vim:set ft=dockerfile:
FROM registry.cn-hongkong.aliyuncs.com/imxieke/ubuntu:bionic

# for MariaDB 10+
ENV GPG_KEYS \
	177F4010FE56CA3336300305F1656F24C74CD1D8 \
	430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A \
	4D1BB29D63D98E422B2113B19334A25F8507EFA5

# bashbrew-architectures: amd64 arm64v8 ppc64le
ENV MARIADB_MAJOR 10.1
ENV MARIADB_VERSION 1:10.1.37+maria-1~bionic
COPY script/startup.sh /bin/entrypoint.sh

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN set -ex \
	&& groupadd -r mysql \
	&& useradd -r -g mysql mysql \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends gnupg dirmngr \
	&& export GNUPGHOME="$(mktemp -d)"; \
	for key in $GPG_KEYS; do \
		gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
	done; \
	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mariadb.gpg; \
	command -v gpgconf > /dev/null && gpgconf --kill all || :; \
	rm -r "$GNUPGHOME"; \
	echo "deb http://mirrors.ustc.edu.cn/mariadb/repo/$MARIADB_MAJOR/ubuntu bionic main" > /etc/apt/sources.list.d/mariadb.list \
	&& apt-get update \
	&& apt-get install -y mariadb-server="$MARIADB_VERSION" \
	# sed -ri 's/^user\s/#&/' /etc/mysql/my.cnf /etc/mysql/conf.d/*; \
	# don't reverse lookup hostnames, they are usually another container
	# echo '[mysqld]\nskip-host-cache\nskip-name-resolve' > /etc/mysql/conf.d/docker.cnf \
	&& rm -fr /etc/mysql/my.cnf \
	&& rm -fr /var/lib/mysql \
	# purge and re-create /var/lib/mysql with appropriate ownership
	&& mkdir -p /var/lib/mysql  \
	&& mkdir -p /var/run/mysqld  \
	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
	# ensure that /var/run/mysqld (used for socket and lock files) is writable regardless of the UID our mysqld instance ends up having at runtime
	&& chmod 777 /var/run/mysqld \
	# comment out a few problematic configuration values
	&& find /etc/mysql/ -name '*.cnf' -print0 | xargs -0 grep -lZE '^(bind-address|log)' | xargs -rt -0 sed -Ei 's/^(bind-address|log)/#&/' \
	&& chmod +x /bin/entrypoint.sh \
	# && apt-get purge -y --auto-remove ca-certificates gnupg dirmngr \
	&& apt autoremove -y \
	&& apt-get clean all \
	&& rm -fr /var/lib/apt/lists/*

COPY conf/my.cnf-10.4 /etc/mysql/my.cnf
VOLUME /var/lib/mysql
ENTRYPOINT ["/bin/entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]