FROM mcr.microsoft.com/powershell:lts-ubuntu-22.04

LABEL MAINTAINER="Cloudflying" \
    MAIL="oss@live.hk" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv \
    org.opencontainers.image.description='PowerShell'

CMD ["pwsh"]
