version: '2'
services:
    workspace:
        build:
            context: ./workspace
        volumes_from:
            - volumes_source
            - volumes_data
        tty: true

    memcached:
        build:
            context: ./memcached
        container_name: memcached
        volumes_from:
            - volumes_data

#    redis:
#        build:
#            context: ./redis
#        volumes_from:
#            - volumes_data
#        ports:
#            - 6379:6379
#
    mysql:
        build:
            context: ./mysql
        ports:
            - "3306:3306"
        volumes_from:
            - volumes_data
        environment:
            MYSQL_DATABASE: topone4tvs
            MYSQL_USER: topone4tvs
            MYSQL_PASSWORD: chenbowen
            MYSQL_ROOT_PASSWORD: chenbowen

    php:
        build:
            context: ./php
        links:
            - workspace
            - memcached
              #- redis
              #- mysql
        volumes_from:
            - volumes_source

    php7:
        image: dev-php7-v1
        build:
            context: ./php7
            args:
                - LOCAL_IP_ADD=10.10.111.152
        links:
            - workspace
            - memcached
              #- redis
              #- mysql
        volumes_from:
            - volumes_source
            - volumes_data

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php7
        links:
            - php7
        volumes_from:
            - volumes_source
            - volumes_data
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "8888:8888"
            - "9090:9090"
### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - /private/var/www:/private/var/www

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/nginx:/data/nginx
            - ./data/logs:/data/logs
            - ./data/mysql:/data/mysql
            - ./data/mongodb:/data/mongodb
            - ./data/memcached:/data/memcached
            - ./data/redis:/data/redis
            - ./data/sessions:/data/sessions
