FROM ghcr.io/dockenv/alpine:edge
LABEL MAINTAINER="Cloudflying" \
    MAIL="<oss@live.hk>" \
    org.opencontainers.image.source=https://github.com/dockenv/dockenv

RUN apk add --no-cache bash git jq procps bash-completion iputils

CMD [ "/bin/sh" ]
