FROM registry.cn-hongkong.aliyuncs.com/boxs/alpine:latest

LABEL MAINTAINER="Cloudflying" \
        MAIL="oss@live.hk" \
        org.opencontainers.image.source=https://github.com/dockenv/dockenv

RUN apk add --no-cache acme.sh

CMD ["/bin/ash"]
