FROM reg.qiniu.com/imxieke/ubuntu:xenial-vncenv
ENV DEBIAN_FRONTEND noninteractive
ENV MAINTAINER=Cloudflying \
    MAIL=oss@live.hk \
    USER=ubuntu \
    PASSWD=ubuntu \
    SHELL_DIR=tmp/shell \
    TERM=xterm \
    STARTUPDIR=/startup \
    INST_SCRIPTS=/home/ubuntu/install \
    NO_VNC_HOME=/home/ubuntu/.noVNC \
    DEBIAN_FRONTEND=noninteractive \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1360x768 \
    VNC_PW=ubuntu \
    VNC_VIEW_ONLY=false \
    DISPLAY=:1 \
    VNC_PORT=5901 \
    NO_VNC_PORT=6901
ENV HOME=/home/${USER}

# COPY ./unity/supervisor.conf /etc/supervisor/conf.d/
COPY ./unity/xsession ${HOME}/.xsession
COPY ./unity/startup.sh /bin/startup.sh
COPY ./unity/unity.sh ${SHELL_DIR}/

RUN apt-get update \
    && apt-get install -y --no-install-recommends ubuntu-desktop unity-lens-applications gnome-panel metacity nautilus locales gedit  \
    pwgen libtasn1-3-bin libglu1-mesa \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN chmod +x ${SHELL_DIR}/unity.sh \
    && ${SHELL_DIR}/unity.sh

USER ${USER}
EXPOSE ${VNC_PORT} ${NO_VNC_PORT}
ENTRYPOINT ["/bin/bash", "/bin/startup.sh"]
CMD ["--wait"]