FROM registry.cn-hongkong.aliyuncs.com/imxieke/ubuntu:bionic
LABEL MAINTAINER="Cloudflying" \
        MAIL="oss@live.hk"

ENV HOME=/home/${USER}
ADD scripts/install-bt.sh /tmp/build.sh

RUN chmod +x /tmp/build.sh \
	&& bash /tmp/build.sh \
	&& rm -fr /tmp/*

EXPOSE 8888
CMD ["/bin/bash"]