name: Docker Build Alpine

on:
  workflow_dispatch:
    branches:
    - master
  schedule:
    - cron: '0 2 * * *'

env:
  IMAGE_NAME: alpine
  IMAGE_TAGS: "latest edge 3.17 3.16 3.15 3.14 3.13 3.12"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Image
      run: |
        for tag in ${IMAGE_TAGS}; do
          docker build . -f images/${{ env.IMAGE_NAME }}/${tag}/Dockerfile -t ${{ env.DOCKER_REGISTRY_GITHUB }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
        done

    - name: Login to Github Package Registry
      run: |
        docker login -u ${{secrets.USERNAME}} -p "${{ secrets.APIKEY }}" ${{ env.DOCKER_REGISTRY_GITHUB }}

    - name: Push Docker Image To Github Package
      run: |
        for tag in ${IMAGE_TAGS}; do
          docker push ${{ env.DOCKER_REGISTRY_GITHUB }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
        done
